// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// read_sensors //
// ------------ //

#define read_sensors_wrap_target 0
#define read_sensors_wrap 1

static const uint16_t read_sensors_program_instructions[] = {
            //     .wrap_target
    0x4006, //  0: in     pins, 6                    
    0x8020, //  1: push   block                      
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program read_sensors_program = {
    .instructions = read_sensors_program_instructions,
    .length = 2,
    .origin = -1,
};

static inline pio_sm_config read_sensors_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + read_sensors_wrap_target, offset + read_sensors_wrap);
    return c;
}
#endif

