// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// read_sensors //
// ------------ //

#define read_sensors_wrap_target 3
#define read_sensors_wrap 2

static const uint16_t read_sensors_program_instructions[] = {
    0x4001, //  0: in     pins, 1                    
    0x8020, //  1: push   block                      
    0x0000, //  2: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program read_sensors_program = {
    .instructions = read_sensors_program_instructions,
    .length = 3,
    .origin = -1,
};

static inline pio_sm_config read_sensors_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + read_sensors_wrap_target, offset + read_sensors_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

